# Generated by Django 6.0 on 2025-12-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='id',
        ),
    ]
